export 'arguments/driver_argument.dart';
export 'getx/driver_bindings.dart';
export 'getx/driver_controller.dart';
export 'getx/driver_detail_bindings.dart';
export 'getx/driver_detail_controller.dart';
export 'screens/add_driver_screen.dart';
export 'screens/driver_detail_screen.dart';
export 'screens/drivers_screen.dart';
export 'widgets/widgets.dart';
