name: Flutter Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate models
        run: dart run build_runner build --delete-conflicting-outputs


      - name: Build APK
        run: flutter build apk -t lib/main.dart --release --split-per-abi

      - name: List build directory (for debugging)
        run: ls -R build/

      - name: Archive Build Outputs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk

